<?php
return [
    'MASTER_TYPE_ID' => 1,
    'MASTER_TYPE_NAME' => 'MASTER',
    'AFFILIATE_TYPE_ID' => 2,
    'AFFILIATE_TYPE_NAME' => 'AFFILIATE',
    'LOCATION_TYPE_ID' => 3,
    'LOCATION_TYPE_NAME' => 'LOCATION',

    'PLAYER_TYPE_ID' => 5,
    'PLAYER_TYPE_NAME' => 'PLAYER',
    'CASHIER_TYPE_ID' => 6,
    'CASHIER_TYPE_NAME' => 'CASHIER',
    'SHIFT_CASHIER_TYPE_ID' => 23,
    'SHIFT_CASHIER_TYPE_NAME' => 'SHIFT_CASHIER',

    'BACKOFFICE_SUBJECT_TYPE_ID' => 0,
    'PLAYER_SUBJECT_TYPE_ID' => 5,

    //DEVICES
    "PC" => 1,
    "REST" => 2,

    "DEFAULT_RESULTS_PER_PAGE" => 100,
];